namespace Sources.Frameworks.DeepFramework.DeepUiManager.Domain.Enums
{
    public enum UiViewId
    {
        Default = 0,
        GameOver = 1,
        MainMenu = 2,
        Pause = 3,
        Achievements = 4,
        GameCompleted = 5,
        Gameplay = 6,
        Quit = 7,
        Settings = 8,
        Tutorial = 9,
        ScoreTutorial = 10,
        BunkerTutorial = 11,
        EnemySpawnerTutorial = 12,
        AbilityTutorial = 13,
        UpgradeTutorial = 14,
        Hud = 15,
        HudBackground = 16,
        Authorization = 17,
        DailyRewards = 18,
        LeaderBoard = 19,
        MainHud = 20,
        WarningNewGame = 21,
        ContinueGame = 22,
        AdvertisingAfterWave = 23,
        Connect = 24,
        Wait = 25,
        CreateRoom = 26,
        Levels = 27,
        Loading = 28,
        NameInput = 29,
        Party = 30,
        SessionInfo = 31,
        Lobby = 32,
        WarningSaveSettings = 33,
        WarningDefaultSettings = 34,
        DesktopExit = 35,
    }
}